# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5b93897856eae13a84c0166e28af2b9b3e1fe3df819ac8b2e7c39131752bacddbbc81c13bb042cfd5cb66dcdd0e6be564d9ff23713f676fbde47799e32d6eabd

test:
  secret_key_base: 6b158b22afe60c00359c77ea3f455b77e5328f0fd0d5d338570f025a3a90391c8b82939dec1910f443f1fe4be271ee43cae6d0f5248d73ee4fc921bd648083bf

# Do not keep production secrets in the repository,
# instead read values from the environment.

staging:
  secret_key_base: <%= ENV["STAGING_SECRET_KEY_BASE"] %>

staging:
  secret_key_base: <%= ENV["STAGING_SECRET_KEY_BASE"] %>
production:
  secret_key_base: <%= ENV["PRODUCTION_SECRET_KEY_BASE"] %>
